// Central registry of legal/policy page content.
// Used by both the admin WYSIWYG editor (pre-fill) and public LegalPage (fallback).

export const LEGAL_PAGES = [
  {
    slug: 'privacy',
    title: 'Privacy Policy',
    lastUpdated: 'June 2025',
    intro: 'BodaSure Technologies Ltd ("BodaSure", "we", "us") is committed to protecting the privacy and personal data of all users of our platform. This Privacy Policy explains how we collect, use, store, and share your personal information in accordance with the Kenya Data Protection Act, 2019.',
    sections: [
      { heading: '1. Information We Collect', body: 'We collect the following types of personal information:\n\nIdentity Information: Full name, national ID number, date of birth, gender, and ID photo.\n\nContact Information: Phone number, email address, and physical address.\n\nVehicle Information: Motorcycle plate number, logbook details, and owner information.\n\nFinancial Information: Wallet transaction history, payment details, and bank account information.\n\nBiometric Data: Selfie photos for identity verification and facial recognition.\n\nUsage Data: Device information, IP address, app usage patterns, and location data.' },
      { heading: '2. How We Use Your Information', body: 'We use your personal information for the following purposes:\n\nTo verify your identity and prevent fraud.\n\nTo create and manage your BodaSure Wallet and process transactions.\n\nTo issue digital permits and compliance certificates.\n\nTo comply with legal and regulatory requirements, including AML/KYC obligations.\n\nTo provide customer support and resolve disputes.\n\nTo improve our services and develop new features.\n\nTo send you important notifications about your account, transactions, and regulatory updates.' },
      { heading: '3. Data Storage & Security', body: 'Your personal data is stored on secure, cloud-hosted infrastructure with AES-256 encryption at rest and TLS 1.3 in transit. Access to personal data is strictly controlled and logged. We retain personal data for the duration of your account and for the period required by law (typically 7 years for financial records).\n\nBiometric data used for identity verification is processed by our verified third-party provider (IDAnalyzer) and is not stored on our servers beyond the verification result.' },
      { heading: '4. Data Sharing', body: 'We may share your personal information with:\n\nCounty Governments — for registration, compliance, and revenue collection purposes.\n\nSACCOs and Welfare Groups — for membership management, with your consent.\n\nRegulatory Authorities — including the Central Bank of Kenya, NTSA, and the Office of the Data Protection Commissioner, when legally required.\n\nThird-party Service Providers — including licensed payment processors, SMS providers, and identity verification providers, under strict data protection agreements.\n\nWe never sell your personal data to third parties.' },
      { heading: '5. Your Rights', body: 'Under the Kenya Data Protection Act 2019, you have the right to:\n\nAccess: Request a copy of the personal data we hold about you.\n\nRectification: Request correction of inaccurate or incomplete data.\n\nErasure: Request deletion of your personal data, subject to legal retention requirements.\n\nObjection: Object to the processing of your data for specific purposes.\n\nData Portability: Receive your data in a structured, machine-readable format.\n\nTo exercise any of these rights, contact us at help@bodasure.com.' },
      { heading: '6. Cookies', body: 'Our website uses cookies to improve user experience, analyze traffic, and provide security. See our Cookie Policy for details on the types of cookies we use and how to manage them.' },
      { heading: '7. Changes to This Policy', body: 'We may update this Privacy Policy from time to time. We will notify you of any material changes via SMS or email. The latest version is always available on our website.' },
      { heading: '8. Contact', body: 'If you have any questions about this Privacy Policy or how we handle your data, contact our Data Protection Officer at help@bodasure.com or write to us at Trance Towers, Mombasa Road, Nairobi, Kenya.' },
    ],
  },
  {
    slug: 'terms',
    title: 'Terms of Service',
    lastUpdated: 'June 2025',
    intro: 'These Terms of Service ("Terms") govern your use of the BodaSure platform, including our website, mobile application, and all related services. By creating an account or using BodaSure, you agree to these Terms.',
    sections: [
      { heading: '1. Eligibility', body: 'You must be at least 18 years old and a resident of Kenya to use BodaSure. By registering, you confirm that you are legally eligible to use our services and that all information provided is accurate and truthful.' },
      { heading: '2. Account Registration', body: 'To use BodaSure, you must complete the registration process, including:\n\nProviding accurate personal information (name, national ID, phone number).\n\nCompleting identity verification via IDAnalyzer.\n\nCompleting bike and ownership verification (for riders).\n\nSetting up a wallet PIN.\n\nYou are responsible for maintaining the confidentiality of your account credentials and PIN. Notify us immediately of any unauthorized access.' },
      { heading: '3. BodaSure Wallet', body: 'The BodaSure Wallet is a digital wallet powered by our licensed payment partner. By using the wallet, you agree to:\n\nMaintain sufficient funds for all transactions.\n\nNot use the wallet for illegal or fraudulent activities.\n\nAuthorize us to deduct applicable fees from your wallet for transactions.\n\nWallet balances are held by our licensed payment partner. BodaSure does not hold customer funds directly.\n\nWallet limits and fees are published on our Pricing page and may be updated from time to time.' },
      { heading: '4. Permitted Use', body: 'You agree to use BodaSure only for lawful purposes. You must not:\n\nUse the platform for money laundering, fraud, or any illegal activity.\n\nAttempt to bypass identity verification or provide false information.\n\nUse another person\'s identity, vehicle, or wallet without authorization.\n\nReverse engineer, decompile, or attempt to access the source code of the platform.\n\nSpam, harass, or harm other users.\n\nViolation of these terms may result in immediate account suspension and legal action.' },
      { heading: '5. Fees & Charges', body: 'BodaSure charges transaction fees for certain services, including:\n\nCounty fee payments (lipa county).\n\nOwner payments (lipa owner).\n\nFare collection (lipisha).\n\nP2P transfers.\n\nAll fees are transparently displayed before each transaction. Fee structures may be updated with 30 days notice.\n\nPremium rider features (loans, investments, health cover) are available at KES 99/month.' },
      { heading: '6. Liability', body: 'BodaSure provides the platform as a service. We are not liable for:\n\nDisputes between riders and motorcycle owners.\n\nDisputes between riders and passengers.\n\nCounty permit or compliance decisions.\n\nLoan or insurance decisions made by third-party providers.\n\nOur liability is limited to the transaction fees collected for the specific service in question.\n\nWe are not liable for indirect, incidental, or consequential damages.' },
      { heading: '7. Dispute Resolution', body: 'Any disputes arising from these Terms or your use of BodaSure shall be resolved through:\n\nFirst, contacting our support team for resolution.\n\nSecond, mediation through a mutually agreed mediator in Nairobi, Kenya.\n\nFinally, arbitration under the Arbitration Act of Kenya, with Nairobi as the seat of arbitration.\n\nThese Terms are governed by the laws of the Republic of Kenya.' },
      { heading: '8. Account Suspension & Termination', body: 'We reserve the right to suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or if required by law or regulatory authorities. You may close your account at any time by contacting support. Outstanding wallet balances will be settled within 14 days of account closure.' },
      { heading: '9. Changes to Terms', body: 'We may update these Terms from time to time. Material changes will be communicated via SMS or email at least 30 days before they take effect. Continued use of BodaSure after changes take effect constitutes acceptance of the updated Terms.' },
      { heading: '10. Contact', body: 'For questions about these Terms, contact us at help@bodasure.com.' },
    ],
  },
  {
    slug: 'cookies',
    title: 'Cookie Policy',
    lastUpdated: 'June 2025',
    intro: 'This Cookie Policy explains how BodaSure Technologies Ltd uses cookies and similar technologies on our website and mobile application.',
    sections: [
      { heading: '1. What Are Cookies', body: 'Cookies are small text files placed on your device when you visit a website. They help the website remember your actions and preferences over time. We use cookies to improve your experience, analyze traffic, and ensure security.' },
      { heading: '2. Types of Cookies We Use', body: 'Essential Cookies: Required for the website to function correctly. These enable core features like authentication, security, and session management.\n\nAnalytics Cookies: Help us understand how visitors use our website so we can improve performance and user experience. We use anonymized, aggregated data.\n\nPreference Cookies: Remember your settings, such as language and display preferences, to provide a personalized experience.\n\nSecurity Cookies: Monitor for suspicious activity and help protect against fraud and unauthorized access.' },
      { heading: '3. Third-Party Cookies', body: 'We may use third-party services that set their own cookies, including:\n\nAnalytics providers to understand website usage.\n\nPayment providers for transaction security.\n\nIdentity verification providers for fraud prevention.\n\nThese third parties have their own privacy policies governing how they use cookies and data.' },
      { heading: '4. Managing Cookies', body: 'You can control and manage cookies through your browser settings. Most browsers allow you to:\n\nAccept or reject all cookies.\n\nAccept only essential cookies.\n\nDelete existing cookies.\n\nBlock cookies from specific websites.\n\nNote that disabling essential cookies may prevent you from using key features of our website, such as login and registration.' },
      { heading: '5. Updates', body: 'We may update this Cookie Policy from time to time. Changes will be posted on this page with an updated "Last updated" date.' },
      { heading: '6. Contact', body: 'For questions about our use of cookies, contact us at help@bodasure.com.' },
    ],
  },
  {
    slug: 'aml',
    title: 'AML / KYC Policy',
    lastUpdated: 'June 2025',
    intro: 'BodaSure Technologies Ltd is committed to preventing money laundering, terrorist financing, and financial crime. This Anti-Money Laundering (AML) and Know Your Customer (KYC) Policy outlines the procedures we follow to comply with Kenyan financial regulations, including the Proceeds of Crime and Anti-Money Laundering Act and Central Bank of Kenya (CBK) guidelines.',
    sections: [
      { heading: '1. Identity Verification (KYC)', body: 'All BodaSure users must complete identity verification before accessing wallet services. This includes:\n\nNational ID verification: Users must upload their national ID (front and back) for AI-powered verification via IDAnalyzer.\n\nSelfie verification: A live selfie is compared against the ID photo using facial recognition technology.\n\nBiometric liveness check: Ensures the user is physically present during verification.\n\nSanctions screening: User details are screened against international sanctions lists.\n\nFor SACCOs and county government accounts, enhanced due diligence is performed, including verification of business registration, director identities, and beneficial ownership.' },
      { heading: '2. Transaction Monitoring', body: 'BodaSure monitors all wallet transactions for suspicious activity, including:\n\nUnusually large transactions that are inconsistent with a user\'s profile.\n\nRapid movement of funds between accounts (structuring/smurfing patterns).\n\nTransactions involving high-risk jurisdictions.\n\nMultiple failed or reversed transactions.\n\nTransactions flagged by our automated risk scoring system.\n\nSuspicious transactions are reviewed by our compliance team and may be reported to the Financial Reporting Centre (FRC) of Kenya.' },
      { heading: '3. Reporting Obligations', body: 'Under Kenyan law, BodaSure is required to report:\n\nSuspicious Transaction Reports (STRs) to the Financial Reporting Centre within 7 days of detection.\n\nCash Transaction Reports (CTRs) for transactions above the statutory threshold.\n\nTerrorist Property Reports if we identify any property owned or controlled by a terrorist entity.\n\nWe are prohibited from tipping off any person who is the subject of a suspicious transaction report.' },
      { heading: '4. Risk Assessment', body: 'BodaSure conducts periodic risk assessments to identify and mitigate money laundering and terrorist financing risks. Risk factors include:\n\nCustomer risk (e.g., PEPs, high-risk occupations).\n\nGeographic risk (e.g., high-risk jurisdictions).\n\nProduct risk (e.g., anonymous transactions, cross-border transfers).\n\nTransaction risk (e.g., large cash transactions, rapid fund movement).\n\nUsers are assigned a risk rating that determines the level of due diligence and monitoring applied to their account.' },
      { heading: '5. Record Keeping', body: 'BodaSure maintains records of all identity verification documents, transaction records, and compliance reports for a minimum of 7 years, as required by Kenyan law. Records are stored securely and are available to regulatory authorities upon request.' },
      { heading: '6. Employee Training', body: 'All BodaSure employees receive regular AML/KYC training to ensure they understand their obligations and can identify suspicious activity. Training covers:\n\nKenyan AML laws and regulations.\n\nIdentifying red flags and suspicious patterns.\n\nProcedures for reporting suspicious activity.\n\nSanctions screening and PEP identification.' },
      { heading: '7. Compliance Officer', body: 'BodaSure has appointed a designated Compliance Officer responsible for overseeing the AML/KYC program. The Compliance Officer reports to senior management and regulatory authorities as required.\n\nFor AML/KYC inquiries, contact: help@bodasure.com' },
    ],
  },
  {
    slug: 'acceptable-use',
    title: 'Acceptable Use Policy',
    lastUpdated: 'June 2025',
    intro: 'This Acceptable Use Policy sets out the rules for using the BodaSure platform. By using BodaSure, you agree to follow these rules. Violation may result in account suspension, termination, and legal action.',
    sections: [
      { heading: '1. Permitted Activities', body: 'You may use BodaSure for:\n\nRegistering as a BodaBoda rider, SACCO member, or county official.\n\nCompleting identity and vehicle verification.\n\nUsing the BodaSure Wallet for legitimate transactions, including fare collection, county fee payments, and P2P transfers.\n\nAccessing financial services (insurance, loans, investments) through our partner providers.\n\nParticipating in SACCO and chama activities.\n\nAll activities must be lawful and conducted in good faith.' },
      { heading: '2. Prohibited Activities', body: 'You must not:\n\nUse BodaSure for money laundering, terrorism financing, or any illegal activity.\n\nProvide false, inaccurate, or misleading information during registration or verification.\n\nUse another person\'s identity, ID, or wallet without authorization.\n\nRegister a motorcycle that you do not own or have authorization to operate.\n\nCreate fake or duplicate accounts.\n\nAttempt to bypass or circumvent identity verification, transaction limits, or security controls.\n\nUse the platform for gambling, betting, or pyramid schemes.\n\nHarass, threaten, or defame other users.\n\nSend unsolicited messages or spam.\n\nReverse engineer, hack, or attempt to access the platform\'s source code or infrastructure.\n\nResell or commercialize your BodaSure account without authorization.' },
      { heading: '3. Content Standards', body: 'When posting content on BodaSure (e.g., profile photos, bike photos, dispute descriptions):\n\nContent must be accurate and truthful.\n\nContent must not be defamatory, obscene, or offensive.\n\nContent must not infringe on intellectual property rights.\n\nContent must not contain personal information of third parties without consent.\n\nWe reserve the right to remove any content that violates these standards.' },
      { heading: '4. Enforcement', body: 'Violations of this Acceptable Use Policy may result in:\n\nWarning and requirement to correct the violation.\n\nTemporary suspension of account access.\n\nPermanent account termination.\n\nReporting to law enforcement or regulatory authorities.\n\nRecovery of financial losses caused by the violation.\n\nWe use automated systems and manual review to detect violations. Account actions can be appealed by contacting help@bodasure.com.' },
      { heading: '5. Changes', body: 'We may update this Acceptable Use Policy from time to time. Changes will be posted on this page with an updated "Last updated" date.' },
      { heading: '6. Contact', body: 'For questions about this policy, contact us at help@bodasure.com.' },
    ],
  },
  {
    slug: 'consumer-protection',
    title: 'Consumer Protection Policy',
    lastUpdated: 'June 2026',
    intro: 'BodaSure Technologies Ltd ("BodaSure", operated by Mint Mobitech) is committed to fair treatment of all financial consumers in accordance with the Kenya Financial Consumer Protection Framework (March 2026), the National Payment System Act 2011, CBK Prudential Guidelines, and the Consumer Protection Act 2012.',
    sections: [
      { heading: '1. Our Commitment to Fair Treatment', body: 'We treat all riders, SACCO members, motorcycle owners, and county partners fairly and without discrimination. We design products that meet genuine financial needs. We communicate in plain language (English and Swahili). We never use aggressive, misleading, or high-pressure sales tactics. Every user is entitled to a clear explanation of any product or service before committing.' },
      { heading: '2. Scope of This Policy', body: 'This policy applies to all users of the BodaSure platform including riders, SACCO officials, motorcycle owners, county government officers, merchants, and field agents. It covers all financial services offered through BodaSure: BodaSure Wallet (powered by SasaPay), fare collection (Lipisha), county levy payments (Lipa County), motorcycle owner payments (Lipa Owner), SACCO and chama contributions, insurance products, and penalty payments.' },
      { heading: '3. Transparent Pricing & Fee Disclosure', body: 'All transaction fees are displayed prominently to the user before any payment is confirmed — no hidden charges. Fee schedules are published at bodasure.com/pricing. Any change to fees is communicated to users via SMS at least 30 days before taking effect. At point of transaction, fee breakdowns include: the platform service fee, the SasaPay processing fee, and where applicable, the split between county revenue, SACCO allocation, and platform commission.' },
      { heading: '4. Wallet & Funds Safety', body: 'BodaSure Wallet balances are held by SasaPay (Viewtech Limited), a Payment Service Provider licensed by the Central Bank of Kenya under the National Payment System Act 2011. BodaSure does not hold, commingle, or lend customer funds. Customer float is ring-fenced in a designated trust account maintained by SasaPay. In the event that BodaSure ceases operations, user funds held within the SasaPay system remain fully protected and are returnable to users in accordance with CBK guidelines.' },
      { heading: '5. Data Protection Rights', body: 'All personal data is collected and processed in accordance with the Kenya Data Protection Act 2019 and the Office of the Data Protection Commissioner guidelines. Users have the right to: access a copy of their personal data; request correction of inaccurate data; request deletion of data (subject to legal retention requirements); object to specific uses of their data; and receive their data in a portable format. Biometric data (selfie and ID photos) is used solely for identity verification and is not retained on BodaSure servers beyond the verification result. Our Data Protection Officer is contactable at help@bodasure.com.' },
      { heading: '6. Vulnerable Consumer Protections', body: 'BodaSure recognises that many bodaboda riders are first-time users of digital financial services and may be especially susceptible to digital fraud, mis-selling, or over-commitment. We apply the following specific protections: all onboarding is conducted in plain language; Swahili-language support is available via phone and SMS; SMS confirmations are sent for every wallet transaction; no financial product is upsold during the registration or onboarding process; customer support by phone and email is provided at no cost to the user; and transaction limits are set at conservative levels aligned with CBK tiered KYC thresholds.' },
      { heading: '7. Transaction Limits & Consumer Safeguards', body: 'Daily and per-transaction wallet limits apply to all account tiers, set in alignment with CBK tiered KYC requirements. Tier 1 (Basic registration, no wallet): access to platform features only, no financial transactions. Tier 2 (ID-verified): standard daily and per-transaction limits as published on the pricing page. Enhanced limits are available upon full KYC completion. All limits are disclosed at account opening, during onboarding, and on the pricing page. Limits may be adjusted periodically following CBK guidance, with notice to users.' },
      { heading: '8. Prohibition of Unfair Practices', body: 'BodaSure explicitly prohibits the following: unsolicited or coercive upselling of financial products; opaque or misleading fee structures; deceptive advertising or misrepresentation of product terms; withholding material information that would affect a consumer\'s decision; use of personal data for undisclosed commercial purposes; and discriminatory treatment of any user on the basis of gender, ethnicity, religion, disability, or geographic location.' },
      { heading: '9. Right to Exit', body: 'Any user may request closure of their BodaSure account at any time, without penalty or fee, by contacting help@bodasure.com. Upon closure: outstanding wallet balances are settled to the user\'s registered M-Pesa number within 14 working days; active county permits remain valid until their expiry date; SACCO memberships are handled in accordance with the relevant SACCO\'s own rules; and all personal data is handled per our Privacy Policy and the Kenya Data Protection Act 2019.' },
      { heading: '10. Regulatory Oversight', body: 'BodaSure\'s payment services are provided through SasaPay (Viewtech Limited), licensed by the Central Bank of Kenya. BodaSure Technologies Ltd (operated by Mint Mobitech) is a registered entity under the laws of Kenya. For regulatory enquiries, contact: help@bodasure.com | 0701 200 500 | Trance Towers, Mombasa Road, Nairobi.' },
      { heading: '11. Policy Review', body: 'This policy is reviewed annually and immediately upon any material change to applicable law or CBK regulation. Last updated: June 2026.' },
    ],
  },
  {
    slug: 'refund-policy',
    title: 'Refund Policy',
    lastUpdated: 'June 2026',
    intro: 'BodaSure Technologies Ltd is committed to clear, fair, and timely resolution of all refund requests. This policy governs refunds for all financial transactions on the BodaSure platform — including wallet deposits, county levy payments, owner payments, fare collections, SACCO contributions, insurance premiums, and penalty payments — in accordance with the Kenya Financial Consumer Protection Framework (March 2026), the National Payment System Act 2011, and CBK Prudential Guidelines.',
    sections: [
      { heading: '1. Scope of This Policy', body: 'This policy applies to all refund requests arising from transactions processed through the BodaSure platform, whether initiated by the user, by BodaSure, or by a counterparty (county government, SACCO, motorcycle owner, or merchant). It covers: failed or reversed wallet transactions; duplicate payments for county permits; overpayments to motorcycle owners; disputed fare collections; failed SACCO or chama contributions; cancelled insurance policies within the cooling-off period; and penalties disputed and subsequently waived.' },
      { heading: '2. Eligibility for Refunds', body: 'A user may be eligible for a refund where: a transaction was debited but not delivered to the intended recipient due to a system error; a duplicate payment was made for the same permit or service; the user was charged an incorrect fee amount; a county permit was paid for but could not be issued due to a registration issue on the county side; an insurance premium was deducted but the policy was not activated; or a penalty was paid and subsequently overturned through the disputes redress process.' },
      { heading: '3. Non-Refundable Transactions', body: 'The following are generally not eligible for refund: successfully completed fare collections (Lipisha) where the rider has already received the funds; county permit payments where the permit has been issued and is active; SACCO or chama contributions that have already been disbursed to the group wallet; transaction fees and platform service fees for successfully completed transactions; and penalties that have been upheld through the disputes process. In exceptional circumstances, BodaSure may exercise discretion to issue a goodwill refund.' },
      { heading: '4. Refund Initiation', body: 'To request a refund, the user must contact BodaSure customer support within 60 days of the transaction date via any of the following channels: email to help@bodasure.com; phone call to 0701 200 500; or in-app support ticket. The user must provide: the transaction reference number, the date and amount of the transaction, and a brief description of the reason for the refund request.' },
      { heading: '5. Refund Processing Timeline', body: 'BodaSure will acknowledge all refund requests within 48 hours of receipt. Validated refund requests will be processed within the following timelines: failed or reversed wallet transactions — refunded to the user\'s BodaSure Wallet within 3 working days; refunds to M-Pesa — processed within 5 working days via SasaPay B2C transfer; county permit refunds — processed within 10 working days, subject to county government confirmation; and insurance premium refunds — processed within 14 working days, subject to the insurance provider\'s own refund policy.' },
      { heading: '6. Refund Method', body: 'Refunds are processed back to the original source of funds wherever possible: wallet-funded transactions are refunded to the BodaSure Wallet; M-Pesa-funded transactions are refunded to the user\'s registered M-Pesa number via SasaPay B2C; and bank-funded transactions are refunded to the user\'s bank account. Where the original source is unavailable (e.g., the user\'s M-Pesa line is inactive), the refund will be credited to the user\'s BodaSure Wallet and the user notified via SMS.' },
      { heading: '7. Partial Refunds', body: 'Where a transaction is partially eligible for refund (e.g., an overpayment to a county permit where the correct fee is lower than the amount paid), BodaSure will refund the difference to the user\'s original payment method. The user will receive an SMS confirmation with the refund amount and reference number.' },
      { heading: '8. Refund Status Tracking', body: 'Users can track the status of their refund request by contacting customer support and quoting their request reference number. Refund status updates are: Request Received — acknowledgement sent; Under Review — being validated by our team; Approved — refund has been authorised for processing; Processed — funds have been dispatched to the user; and Completed — funds have been received by the user.' },
      { heading: '9. Disputed Refund Decisions', body: 'If a user disagrees with BodaSure\'s refund decision, they may escalate the matter through our Complaints Redress Mechanism (available at bodasure.com/complaints-redress). The user may also lodge a complaint with the Central Bank of Kenya or the Office of the Data Protection Commissioner where the matter relates to a regulated financial service or data protection concern respectively.' },
      { heading: '10. Fraud & Chargeback Prevention', body: 'BodaSure reserves the right to decline refund requests that are found to be fraudulent, made in bad faith, or part of an attempt to exploit the refund process. Users who submit fraudulent refund requests may have their accounts suspended and may be reported to the relevant authorities. All refund decisions are logged and auditable.' },
      { heading: '11. Policy Review', body: 'This Refund Policy is reviewed annually and immediately upon any material change to applicable law or CBK regulation. Last updated: June 2026.' },
    ],
  },
  {
    slug: 'complaints-redress',
    title: 'Complaints Redress Mechanism',
    lastUpdated: 'June 2026',
    intro: 'BodaSure Technologies Ltd is committed to providing a fair, accessible, and timely complaints redress mechanism for all users. This policy is established in accordance with the Kenya Financial Consumer Protection Framework (March 2026), the National Payment System Act 2011, CBK Prudential Guidelines on Complaints Handling, and the Kenya Arbitration Act.',
    sections: [
      { heading: '1. Our Commitment', body: 'Every user of the BodaSure platform — rider, SACCO official, motorcycle owner, county officer, merchant, or field agent — has the right to raise a complaint and have it resolved fairly, promptly, and at no cost. We are committed to: acknowledging all complaints within 48 hours; resolving complaints at the earliest possible stage; providing clear reasons for our decisions; and ensuring that no user faces retaliation or disadvantage for raising a complaint in good faith.' },
      { heading: '2. What You Can Complain About', body: 'You may lodge a complaint about any aspect of the BodaSure platform, including: unauthorised or incorrect wallet transactions; delayed or failed payments; disputes over county permit fees or validity; disputes over motorcycle owner payment splits; incorrect or unfair penalty charges; poor customer service or unprofessional conduct by BodaSure staff or agents; privacy or data protection concerns; SACCO membership or contribution disputes processed through the platform; and insurance product or claim disputes routed through BodaSure.' },
      { heading: '3. How to Lodge a Complaint', body: 'Complaints may be submitted through any of the following channels: Email — help@bodasure.com; Phone — 0701 200 500 (available Monday to Saturday, 8am to 8pm); In-App — support ticket via the BodaSure app under Support; or Post — BodaSure Technologies Ltd, Trance Towers, Mombasa Road, Nairobi, Kenya. When lodging a complaint, please provide: your full name and registered phone number; the date and nature of the issue; the transaction reference number(s) if applicable; and the outcome you are seeking.' },
      { heading: '4. Complaint Resolution Process', body: 'Our complaints process follows three stages: Stage 1 (Frontline Resolution) — most complaints are resolved at first contact by our customer support team within 48 hours. Stage 2 (Internal Review) — if the complaint is not resolved at Stage 1, it is escalated to a senior team member for investigation. A written response is provided within 7 working days. Stage 3 (Management Review) — if the user is still not satisfied, the complaint is reviewed by the BodaSure Management Committee. A final written decision is issued within 21 working days of the original complaint.' },
      { heading: '5. Acknowledgement & Updates', body: 'Every complaint receives an automatic acknowledgement with a unique reference number within 48 hours of submission. The user will receive SMS and/or email updates at each stage of the process. If a complaint requires more than 21 working days to resolve, the user will be informed of the delay, given a reason, and provided with a revised expected resolution date.' },
      { heading: '6. Confidentiality & Non-Retaliation', body: 'All complaints are handled in strict confidence. Personal information provided in the course of a complaint is used solely for the purpose of investigating and resolving the complaint. No user will face retaliation, service degradation, or any form of disadvantage for raising a complaint in good faith. BodaSure staff are prohibited from discussing a complainant\'s identity or complaint details outside the authorised investigation team.' },
      { heading: '7. Escalation to External Bodies', body: 'If a user is not satisfied with BodaSure\'s final decision, or if 21 working days have elapsed without resolution, the user may escalate the complaint to the following external bodies: Central Bank of Kenya — for complaints relating to payment services provided through SasaPay (Viewtech Limited), licensed under the National Payment System Act 2011. Office of the Data Protection Commissioner — for complaints relating to personal data handling under the Kenya Data Protection Act 2019. SASRA — for complaints relating to SACCO operations. Competition Authority of Kenya — for complaints relating to unfair trade practices under the Consumer Protection Act 2012.' },
      { heading: '8. Arbitration', body: 'Where a complaint cannot be resolved through the internal process or external mediation, the matter shall be referred to arbitration under the Arbitration Act of Kenya (Cap 49, Laws of Kenya). The arbitration shall be: conducted by a single arbitrator agreed upon by both parties, or appointed by the Nairobi Centre for International Arbitration (NCIA) if the parties cannot agree; seated in Nairobi, Kenya; conducted in English; and conducted in accordance with the NCIA Arbitration Rules. The arbitrator\'s award shall be final and binding on both parties. Nothing in this section prevents a user from seeking interim or injunctive relief from a court of competent jurisdiction where urgently necessary.' },
      { heading: '9. Compensation', body: 'Where BodaSure is found to be at fault, we will provide appropriate remediation, which may include: full refund of the disputed amount; reversal of any fees or charges incorrectly applied; a goodwill credit to the user\'s BodaSure Wallet; and a written apology. Compensation is determined on a case-by-case basis, taking into account the nature and impact of the issue, any financial loss suffered by the user, and applicable regulatory guidance.' },
      { heading: '10. Reporting & Transparency', body: 'BodaSure maintains a complaints register and publishes aggregated, anonymised complaints data in our annual consumer protection report. This includes: total number of complaints received; percentage resolved at each stage; average resolution time; and categories of complaints. This transparency ensures accountability and drives continuous improvement in our services.' },
      { heading: '11. Vulnerable Consumers', body: 'BodaSure provides additional support to users who may require assistance in lodging or pursuing a complaint, including: Swahili-language support for all complaint channels; assistance from a designated support officer for first-time digital financial service users; and flexibility in documentation requirements where the user is unable to provide standard supporting evidence.' },
      { heading: '12. Policy Review', body: 'This Complaints Redress Mechanism is reviewed annually and immediately upon any material change to applicable law or CBK regulation. Last updated: June 2026.' },
    ],
  },
  {
    slug: 'data-protection',
    title: 'Data Protection Policy',
    lastUpdated: 'July 2026',
    intro: 'BodaSure Technologies Ltd ("BodaSure", operated by Mint Mobitech) is a registered Data Controller and Data Processor under the Kenya Data Protection Act 2019 (Act No. 24 of 2019) and is registered with the Office of the Data Protection Commissioner (ODPC). This Data Protection Policy explains our obligations, your rights, and the specific measures we take to protect the personal data of all riders, SACCO members, motorcycle owners, county government partners, merchants, and field agents who use the BodaSure platform.',
    sections: [
      { heading: '1. Legal Framework and Registration', body: 'BodaSure processes personal data in compliance with the Kenya Data Protection Act 2019 (the "Act"), the Data Protection (General) Regulations 2021, the Data Protection (Registration of Data Controllers and Data Processors) Regulations 2021, and all guidelines issued by the Office of the Data Protection Commissioner (ODPC). As required by Section 15 of the Act, BodaSure is registered as a Data Controller and Data Processor with the ODPC. Our registration covers the processing of personal and sensitive personal data for the purposes of digital financial services, identity verification, county permit administration, and SACCO management.\n\nWe have appointed a designated Data Protection Officer (DPO) in accordance with Section 24 of the Act. Our DPO is contactable at: help@bodasure.com | 0701 200 500 | Trance Towers, Mombasa Road, Nairobi, Kenya.' },
      { heading: '2. Categories of Personal Data We Process', body: 'BodaSure processes the following categories of personal data, collected directly from users during registration, onboarding, and platform use:\n\nIdentity Data: Full legal name, national ID number, date of birth, gender, nationality, and ID card photographs (front and back).\n\nBiometric Data (Sensitive): Selfie photographs used for facial recognition and liveness detection during identity verification. Biometric data is classified as sensitive personal data under Section 2 of the Act and is subject to heightened protection.\n\nContact Data: Mobile phone number, email address, and physical address.\n\nVehicle Data: Motorcycle plate number, logbook details, make, model, colour, and ownership status.\n\nFinancial Data: Wallet transaction history, M-Pesa numbers, payment references, SasaPay account identifiers, county permit payment records, SACCO contribution records, and insurance premium records.\n\nCompliance Data: County permit status, enforcement penalty records, compliance scores, and SACCO membership status.\n\nDevice and Usage Data: Device type, IP address, app version, session times, and feature usage patterns.\n\nThird-Party Provided Data: Where a motorcycle owner provides a rider\'s details, or a SACCO official provides member details, BodaSure processes this third-party-provided data under the same protections afforded to directly collected data.\n\nWe do not collect data beyond what is necessary for the stated purposes (data minimisation principle, Section 25(b) of the Act).' },
      { heading: '3. Lawful Basis for Processing', body: 'BodaSure processes personal data only where a lawful basis under Section 30 of the Act exists. The lawful bases we rely on are:\n\nConsent (Section 30(a)): We obtain freely given, specific, informed, and unambiguous consent from users during registration for the collection and processing of biometric data, and for marketing communications. Consent may be withdrawn at any time by contacting help@bodasure.com.\n\nContractual Necessity (Section 30(b)): Processing is necessary to provide the services a user has signed up for, including wallet activation, permit payments, fare collection, and SACCO membership management.\n\nLegal Obligation (Section 30(c)): Processing is required to comply with Kenya\'s Anti-Money Laundering (AML) and Know Your Customer (KYC) obligations, CBK regulatory requirements, NTSA vehicle registration requirements, and ODPC reporting obligations.\n\nLegitimate Interests (Section 30(f)): Processing for fraud prevention, platform security, and abuse detection where such interests are not overridden by the rights of the data subject.\n\nWe do not rely on consent for processing that is required by law or contractual necessity. For sensitive personal data (biometrics), we rely exclusively on explicit, written consent (Section 31 of the Act).' },
      { heading: '4. Purpose Limitation', body: 'Personal data collected by BodaSure is used only for the specific purposes for which it was collected, in accordance with Section 25(b) of the Act. These purposes are:\n\nVerifying the identity of riders, SACCO members, and other users (KYC).\n\nActivating and managing the BodaSure Wallet and processing financial transactions.\n\nIssuing and managing digital county permits and compliance records.\n\nManaging SACCO and chama membership registers, contributions, and group wallets.\n\nComplying with AML, counter-terrorism financing, and sanctions screening obligations.\n\nEnabling county government partners to administer registration, compliance, and revenue collection within their jurisdiction.\n\nProcessing insurance, loan, and other financial product applications through licensed partner providers.\n\nProviding customer support and resolving disputes.\n\nImproving platform services through aggregated, anonymised analytics.\n\nPersonal data is never used for undisclosed commercial purposes, profiling for credit scoring by third parties without consent, or sold to any third party.' },
      { heading: '5. Data Retention', body: 'BodaSure retains personal data only for as long as necessary for the purpose for which it was collected, or as required by law (Section 25(d) of the Act).\n\nSpecific retention periods:\n\nIdentity and KYC documents: Retained for a minimum of 7 years after account closure, as required by the Proceeds of Crime and Anti-Money Laundering Act (POCAMLA) and CBK AML guidelines.\n\nFinancial transaction records: Retained for a minimum of 7 years from the date of the transaction, as required by POCAMLA.\n\nBiometric data (facial recognition results): The biometric scan and liveness check are processed by our verified third-party KYC provider (IDAnalyzer/Docupass). Only the verification result (pass/fail and confidence score) is retained on BodaSure\'s servers. Raw biometric images are not stored on BodaSure\'s infrastructure beyond the verification event.\n\nWallet and permit records: Retained for the duration of the account plus 7 years.\n\nUsage and device data: Retained for 12 months for security and fraud prevention purposes.\n\nMarketing communication records: Retained until consent is withdrawn plus 3 years.\n\nUpon expiry of the applicable retention period, personal data is securely deleted or irreversibly anonymised.' },
      { heading: '6. Data Security Measures', body: 'BodaSure implements appropriate technical and organisational security measures to protect personal data against unauthorised access, loss, destruction, or disclosure, in accordance with Section 41 of the Act.\n\nTechnical measures include:\n\nEncryption at rest: All personal data stored on BodaSure\'s cloud infrastructure is encrypted using AES-256 encryption.\n\nEncryption in transit: All data transmitted between the user\'s device and our servers uses TLS 1.3 or higher.\n\nAccess control: Role-based access control (RBAC) ensures that only authorised personnel with a legitimate business need can access personal data. Access rights are reviewed quarterly and revoked immediately upon role change or termination.\n\nAudit logging: All access to and modifications of personal data are logged and retained for security audit purposes.\n\nNetwork security: Firewalls, intrusion detection/prevention systems, and regular vulnerability scanning protect our infrastructure.\n\nSecure development: All code changes undergo security review and are deployed through automated CI/CD pipelines with security gates.\n\nOrganisational measures include:\n\nStaff training: All BodaSure staff receive mandatory data protection training on induction and annually thereafter, covering the Act, ODPC guidelines, and internal data handling procedures.\n\nConfidentiality agreements: All staff and contractors are bound by confidentiality obligations that survive termination of their engagement.\n\nData Protection Officer: Our DPO oversees compliance with the Act, conducts periodic data protection impact assessments (DPIAs), and serves as the primary contact for the ODPC and data subjects.\n\nIncident response: BodaSure maintains a documented incident response plan for suspected or confirmed data breaches, including containment, investigation, notification, and remediation procedures.' },
      { heading: '7. Data Sharing and Disclosure', body: 'BodaSure does not sell personal data to any third party. We share personal data only where necessary and lawful, under strict data protection agreements, with the following categories of recipients:\n\nLicensed Payment Providers: SasaPay (Viewtech Limited), licensed by the Central Bank of Kenya, processes wallet transactions and holds customer float. SasaPay processes personal data as an independent Data Controller/Processor under its own registration with the ODPC.\n\nIdentity Verification Providers: IDAnalyzer/Docupass processes ID card images and selfie photographs for the sole purpose of identity verification. The provider is contractually prohibited from retaining or reusing biometric data beyond the verification event.\n\nCounty Governments: Rider registration data, permit status, and compliance records are shared with the relevant county government for the purpose of administering county transport permits and revenue collection within their jurisdiction.\n\nSACCOs and Chamas: Where a user is a member of a SACCO, limited membership and contribution data is shared with the SACCO\'s authorised officials for the purpose of group administration, subject to the user\'s membership.\n\nRegulatory Authorities: Personal data is disclosed to the Central Bank of Kenya, the Office of the Data Protection Commissioner, the Financial Reporting Centre, NTSA, and other lawful authorities when required by law, court order, or regulatory obligation.\n\nSMS and Communications Providers: Phone numbers are shared with licensed SMS gateway providers (Africa\'s Talking) solely for the purpose of delivering transactional and OTP messages.\n\nAll third-party data processors are engaged under written data processing agreements that require compliance with the Act and prohibit further processing of personal data for their own purposes.' },
      { heading: '8. Cross-Border Data Transfers', body: 'BodaSure primarily stores and processes personal data within cloud infrastructure located in compliance with Kenyan data protection requirements. Where any personal data is processed outside Kenya (for example, by IDAnalyzer or cloud infrastructure with regional failover), BodaSure ensures that:\n\nThe receiving country provides an adequate level of data protection, or\n\nAppropriate safeguards are in place, including standard contractual clauses or binding corporate rules, and\n\nThe transfer is necessary for the provision of the service the user has requested.\n\nBodaSure does not transfer personal data to jurisdictions listed as inadequate by the ODPC. Users may request information about cross-border transfers by contacting our DPO at help@bodasure.com.' },
      { heading: '9. Your Rights as a Data Subject', body: 'Under Part V of the Kenya Data Protection Act 2019, you have the following rights regarding your personal data:\n\nRight to be Informed (Section 26): You have the right to be informed about how your personal data is collected, used, and shared. This Policy and our Privacy Policy fulfil this obligation.\n\nRight of Access (Section 27): You may request a copy of the personal data we hold about you, free of charge, once per calendar year. Requests are fulfilled within 7 working days.\n\nRight to Rectification (Section 28): You may request correction of any inaccurate or incomplete personal data. BodaSure will rectify the data within 7 working days of verification.\n\nRight to Erasure (Section 29): You may request deletion of your personal data, subject to legal retention requirements (e.g., AML/KYC records must be retained for 7 years). Where erasure is not possible due to legal obligations, BodaSure will restrict further processing.\n\nRight to Object (Section 30(3)): You may object to the processing of your personal data for direct marketing or any processing based on legitimate interests. BodaSure will cease such processing upon receipt of your objection.\n\nRight to Data Portability: You may request your personal data in a structured, commonly used, and machine-readable format, and you may transmit that data to another data controller.\n\nRights Related to Automated Decision-Making: You have the right not to be subject to a decision based solely on automated processing that produces legal or similarly significant effects, except where necessary for a contract, authorised by law, or based on your explicit consent.\n\nTo exercise any of these rights, contact our Data Protection Officer at help@bodasure.com or 0701 200 500. BodaSure will respond to all requests within the timelines prescribed by the Act and the Data Protection (General) Regulations 2021.' },
      { heading: '10. Biometric Data and Sensitive Personal Data', body: 'Biometric data (selfie photographs used for facial recognition and liveness detection) is classified as sensitive personal data under Section 2 of the Act and is subject to heightened protection under Section 31.\n\nBodaSure processes biometric data exclusively on the basis of explicit, written consent obtained during the registration process. Users are informed that:\n\nThe biometric data is used solely for identity verification (matching the selfie to the ID photograph and performing a liveness check).\n\nThe processing is performed by our verified third-party KYC provider (IDAnalyzer/Docupass).\n\nRaw biometric images are not stored on BodaSure\'s servers beyond the verification event.\n\nOnly the verification result (pass/fail and confidence score) is retained.\n\nUsers may withdraw consent for future biometric processing at any time, though withdrawal may prevent access to wallet and financial services that require identity verification under CBK regulations.\n\nBodaSure does not use biometric data for any purpose other than identity verification, including profiling, surveillance, or commercial analytics.' },
      { heading: '11. Data Breach Notification', body: 'In the event of a personal data breach (a breach of security leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to personal data), BodaSure follows the notification procedures prescribed by Section 43 of the Act and the Data Protection (General) Regulations 2021:\n\nNotification to the ODPC: BodaSure will notify the Office of the Data Protection Commissioner of any personal data breach within 72 hours of becoming aware of the breach, where the breach is likely to result in a risk to the rights and freedoms of data subjects.\n\nNotification to Data Subjects: Where a personal data breach is likely to result in a high risk to the rights and freedoms of data subjects, BodaSure will communicate the breach to the affected data subjects without undue delay. The communication will describe the nature of the breach, the likely consequences, the measures taken or proposed, and the steps the data subject can take to protect themselves.\n\nBreach Documentation: BodaSure maintains an internal breach register documenting all personal data breaches, including the facts relating to the breach, its effects, and the remedial action taken. This register is available to the ODPC upon request.\n\nExceptions: Notification to data subjects is not required where BodaSure has implemented appropriate technical and organisational protection measures (e.g., encryption) that render the data unintelligible to unauthorised persons, or where subsequent measures have been taken to ensure the high risk is no longer likely to materialise.' },
      { heading: '12. Children\'s Data', body: 'BodaSure is a platform for adults aged 18 years and above. In accordance with Section 33 of the Act, BodaSure does not knowingly process the personal data of children (defined as individuals under 18 years of age).\n\nAge verification: Users must confirm they are 18 or older during registration. National ID verification (which is only available to Kenyan adults 18+) serves as an additional control.\n\nThird-party-provided data: Where a motorcycle owner or SACCO official provides details of another individual, they are responsible for confirming that the individual is 18 or older before submitting their data.\n\nIf BodaSure becomes aware that it has inadvertently processed the personal data of a child, the data will be deleted immediately and the processing ceased.' },
      { heading: '13. Data Protection Impact Assessments (DPIAs)', body: 'BodaSure conducts Data Protection Impact Assessments in accordance with Section 31 of the Data Protection (General) Regulations 2021 for all processing activities that are likely to result in a high risk to the rights and freedoms of data subjects. This includes:\n\nLarge-scale processing of sensitive personal data (including biometric data).\n\nSystematic monitoring of publicly accessible areas.\n\nIntroduction of new technologies or processing systems.\n\nSignificant changes to existing processing activities.\n\nDPIAs are conducted by our Data Protection Officer and reviewed by senior management. The results of DPIAs inform the implementation of additional safeguards where identified risks are not adequately mitigated by existing controls.' },
      { heading: '14. Cookies and Tracking Technologies', body: 'BodaSure uses cookies and similar tracking technologies on its website for essential functionality, security, analytics, and user preference management. The use of cookies is governed by our separate Cookie Policy, available at bodasure.com/cookies.\n\nIn accordance with the Act and ODPC guidance, BodaSure:\n\nObtains consent for non-essential cookies before they are set.\n\nProvides clear information about the types of cookies used and their purpose.\n\nAllows users to withdraw cookie consent at any time.\n\nDoes not use cookies to collect sensitive personal data without explicit consent.\n\nOur mobile application does not use third-party advertising SDKs or tracking technologies that share personal data with advertising networks.' },
      { heading: '15. Complaints to the ODPC', body: 'If you believe that BodaSure has processed your personal data in a manner that violates the Kenya Data Protection Act 2019, you have the right to lodge a complaint with the Office of the Data Protection Commissioner (ODPC).\n\nWe encourage you to first contact our Data Protection Officer at help@bodasure.com so that we may investigate and attempt to resolve your concern. However, you are not required to do so before contacting the ODPC.\n\nThe ODPC can be contacted at:\n\nOffice of the Data Protection Commissioner\n\nP.O. Box 30996 - 00100, Nairobi, Kenya\n\nEmail: complaints@odpc.go.ke\n\nPhone: +254 703 034 000\n\nWebsite: www.odpc.go.ke\n\nYou also have the right to seek a judicial remedy if BodaSure has not complied with its obligations under the Act.' },
      { heading: '16. Changes to This Policy', body: 'BodaSure may update this Data Protection Policy from time to time to reflect changes in our processing activities, the Act, ODPC guidelines, or CBK regulations. Material changes will be communicated to users via SMS or email at least 30 days before they take effect. The updated policy will be published on this page with a revised "Last Updated" date.\n\nContinued use of the BodaSure platform after changes take effect constitutes acknowledgement of the updated policy. Where a material change requires fresh consent (e.g., a new processing purpose), BodaSure will obtain consent before commencing the new processing activity.' },
      { heading: '17. Contact', body: 'If you have any questions, concerns, or requests regarding this Data Protection Policy or how BodaSure handles your personal data, please contact our Data Protection Officer:\n\nEmail: help@bodasure.com\n\nPhone: 0701 200 500\n\nAddress: BodaSure Technologies Ltd (Mint Mobitech), Trance Towers, Mombasa Road, Nairobi, Kenya\n\nOur DPO will acknowledge all enquiries within 48 hours and respond substantively within the timelines prescribed by the Kenya Data Protection Act 2019.' },
    ],
  },
];

function escapeHtml(text) {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Convert the structured fallback content into HTML for the WYSIWYG editor pre-fill.
export function sectionsToHtml(page) {
  if (!page) return '';
  let html = '';
  if (page.intro) {
    html += `<p>${escapeHtml(page.intro)}</p>`;
  }
  for (const section of page.sections || []) {
    html += `<h2>${escapeHtml(section.heading)}</h2>`;
    if (typeof section.body === 'string') {
      for (const para of section.body.split('\n\n')) {
        html += `<p>${escapeHtml(para)}</p>`;
      }
    }
  }
  return html;
}

export function getLegalPage(slug) {
  return LEGAL_PAGES.find(p => p.slug === slug);
}